# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/docker
  docker:
  - image: circleci/python:2.7-node-browsers
    environment:
      AWS_ID: 557749971711

jobs:
  ecr:
    <<: *defaults
    steps:
    - checkout
    # Docker in Docker
    - setup_remote_docker # コレを書くことでDocker上にDockerが立ち上がる
    - run: sudo pip install awscli
    - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
    - run: docker build -f docker/nginx/Dockerfile-nginx -t nginx:dev-$CIRCLE_SHA1 .
    - run: docker build -f docker/php-fpm/Dockerfile-php-fpm -t php-fpm:dev-$CIRCLE_SHA1 ./
    - run: docker tag nginx:dev-$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:dev-$CIRCLE_SHA1
    - run: docker tag php-fpm:dev-$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:dev-$CIRCLE_SHA1
    - run: docker push ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:dev-$CIRCLE_SHA1
    - run: docker push ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:dev-$CIRCLE_SHA1

workflows:
  version: 2
  ecr_push:
    jobs:
    - ecr:
        filters:
          branches:
            only: /^master/