# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node-browsers
    environment:
      USER_NAME: root
      HOST_NAME:
    steps:
    - checkout
    - run: ssh root@153.127.34.236 "cd /home/webmaster/pig_allowance_book_core && git pull"

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: /^master/