# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - add_ssh_keys
    - run: ssh-add -l
    - run: ssh root@153.127.34.236
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: /^master/