version: "3"

services:
  nginx-fpm-pig-allowance-book-test:
    ports:
    - "8005:80"
    hostname: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile-nginx-test
    links:
    - php-fpm-sfb-2-test
    depends_on:
    - php-fpm-sfb-2-test
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ../application:/var/www
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
  php-fpm-pig-allowance-book-test:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile-php-fpm
    tty: true
    ports:
    - "10005:9000"
    links:
    - db-sfb-2
    environment:
      TZ: "Asia/Tokyo"
      PGHOST: db-fpm-pig-allowance-book
      PGDATABASE: pig_allowance_book
      PGUSER: webapp
      PGPASSWORD: webapp
      PASSWORD_SECRET_ID: 1
      PASSWORD_SECRET_KEY: fIHnsRRbMC6aodkoI81lDwUtrJc1OTM6iaB72iDe
    volumes:
      - ../application:/var/www
      - /var/www/node_modules
  db-fpm-pig-allowance-book:
    image: postgres:10.1
    ports:
    - "25432:5432"
    environment:
    - "TZ=Asia/Tokyo"
    - "PGTZ=Asia/Tokyo"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=mysecretpassword1234"
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
