version: "3"

volumes:
  php-fpm-pig-allowance-book-syncs:
    external: true

services:
  nginx-pig-allowance-book:
    ports:
      - "8001:80"
      - "10443:443"
    hostname: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile-nginx-test
    links:
      - php-fpm-pig-allowance-book
    depends_on:
      - php-fpm-pig-allowance-book
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ../application:/var/www
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
  php-fpm-pig-allowance-book:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile-php-fpm
    tty: true
    ports:
      - "10004:9000"
    links:
      - db-pig-allowance-book
    environment:
      TZ: "Asia/Tokyo"
      PGHOST: db-pig-allowance-book
      PGDATABASE: pig_allowance_book
      PGUSER: webapp
      PGPASSWORD: webapp
      PASSWORD_SECRET_ID: 1
      PASSWORD_SECRET_KEY: fIHnsRRbMC6aodkoI81lDwUtrJc1OTM6iaB72iDe
    volumes:
      - php-fpm-pig-allowance-book-syncs:/var/www
      - /var/www/node_modules
      - /var/www/storage
      - ./php-fpm/php.ini:/etc/php.ini
  db-pig-allowance-book:
    image: postgres:10.1
    ports:
      - "15432:5432"
    environment:
      - "TZ=Asia/Tokyo"
      - "PGTZ=Asia/Tokyo"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
